mysql:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
    MYSQL_DATABASE: YOUR_DATABASE
  volumes:
    - "./symfony/custom/data:/docker-entrypoint-initdb.d"
symfony:
  build: symfony/
  ports:
    - "8081:80"
  volumes:
    - "./symfony/custom/code:/var/www"
  links:
    - "mysql"
