FROM debian:jessie
MAINTAINER arderyp@gmail.com

# Put dependency files in place
ADD dependencies/oracle /oracle
ADD dependencies/php7 /php7
ADD dependencies/initialize.sh /initialize.sh
ADD custom/code /var/www

# Install container dependencies
RUN echo 'deb http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list		\
    && echo 'deb-src http://packages.dotdeb.org jessie all' >> /etc/apt/sources.list	\
    && apt-key add /php7/dotdeb.gpg							\
    && apt-get update									\
    && apt-get install -y								\
        libaio1										\
        alien										\
        php7.0-dev                                                                      \
        php-pear                                                                        \
        php7.0-cli                                                                      \
        php7.0-common                                                                   \
        php7.0-curl                                                                     \
        php7.0-intl                                                                     \
        php7.0-json                                                                     \
        php7.0-ldap                                                                     \
        php7.0-mcrypt                                                                   \
        php7.0-mysql                                                                    \
    && apt-get clean                                                                    \
    && cd /oracle									\
    && tar xvfz basic_and_devel_rpm_files.12.1.0.2.0.tgz				\
    && alien *.rpm									\
    && dpkg -i *.deb									\
    && echo /usr/lib/oracle/12.1/client64/lib >> /etc/ld.so.conf.d/oracle.conf		\
    && ldconfig										\
    && printf 'instantclient,/usr/lib/oracle/12.1/client64/lib\n' | pecl install oci8	\
    && sed -i 's/\[OCI8\]/\[OCI8\]\nextension=oci8.so/' /etc/php/7.0/cli/php.ini

# Open port
EXPOSE 80

# Define working directory
WORKDIR /var/www

# Run initialization script upon spin up
ENTRYPOINT ["/initialize.sh"]
