FROM debian:jessie
MAINTAINER arderyp@gmail.com

# Put files in place
ADD dependencies/oracle /oracle
ADD dependencies/initialize.sh /initialize.sh
ADD custom/code /var/www

# Install container dependencies
RUN apt-get update && apt-get install -y							\
        libaio1											\
        alien											\
        php5-dev                                                                                \
        php-pear                                                                                \
        php5-cli                                                                                \
        php5-common                                                                             \
        php5-curl                                                                               \
        php5-intl                                                                               \
        php5-json                                                                               \
        php5-ldap                                                                               \
        php5-mcrypt                                                                             \
        php5-mysql                                                                              \
    && apt-get clean                                                                            \
    && cd /oracle										\
    && alien *.rpm										\
    && dpkg -i *.deb										\
    && echo /usr/lib/oracle/12.1/client64/lib >> /etc/ld.so.conf.d/oracle.conf			\
    && ldconfig											\
    && printf 'instantclient,/usr/lib/oracle/12.1/client64/lib\n' | pecl install oci8-2.0.10	\
    && sed -i 's/\[OCI8\]/\[OCI8\]\nextension=oci8.so/' /etc/php5/cli/php.ini

# Open port
EXPOSE 80

# Define working directory
WORKDIR /var/www

# Run initialization script upon spin up
ENTRYPOINT ["/initialize.sh"]
